identifier: sh.cider.misskey-nowplaying
name: Misskey NowPlaying
description: Auto-post now playing from Cider to Misskey
author: cider2misskey
repo: https://github.com/ciderapp/plugin-template-wip
entry:
  "plugin.js":
    type: main
